local c = require("ayune.colors")
local theme = {
	ColorColumn = { bg = c.line },
	Conceal = { fg = c.guide },
	Cursor = { bg = c.line },
	lCursor = { reverse = true },
	CursorIM = { reverse = true },
	CursorColumn = { bg = c.line },
	CursorLine = { bg = c.line },
	Directory = { fg = c.func },
	DiffAdd = { fg = c.string },
	DiffChange = { fg = c.tag },
	DiffDelete = { fg = c.markup },
	DiffText = { fg = c.fg },
	EndOfBuffer = { fg = c.line },
	TermCursor = { reverse = true },
	TermCursorNC = { fg = c.fg, bg = c.bg },
	ErrorMsg = { fg = c.bg, bg = c.error },
	VertSplit = { fg = c.bg },
	Folded = { fg = c.fg_idle },
	FoldColumn = { bg = c.bg },
	SignColumn = { bg = c.bg },
	IncSearch = { bg = c.accent, fg = c.bg },
	Substitute = { bg = c.accent, fg = c.bg },
	LineNr = { fg = c.fg_idle },
	CursorLineNr = { fg = c.accent },
	MatchParen = { fg = c.fg, bg = c.bg },
	ModeMsg = { fg = c.fg, bold = true },
	MsgArea = { fg = c.fg },
	MsgSeparator = { fg = c.fg },
	MoreMsg = { fg = c.fg },
	NonText = { fg = c.line },
	Normal = { fg = c.fg, bg = c.bg },
	NormalFloat = { fg = c.fg, bg = c.bg },
	NormalNC = { fg = c.fg, bg = c.bg },
	Pmenu = { bg = c.line, fg = c.fg },
	PmenuSel = { fg = c.fg, bg = c.selection },
	PmenuSbar = { bg = c.panel, fg = c.fg },
	PmenuThumb = { bg = c.panel, fg = c.fg },
	Question = { fg = c.fg, bold = true },
	QuickFixLine = { fg = c.fg },
	Search = { bg = c.accent, fg = c.bg },
	SpecialKey = { fg = c.panel },
	SpellBad = { fg = c.fg, sp = c.error, underline = true },
	SpellCap = { fg = c.fg, sp = c.error, underline = true },
	SpellRare = { fg = c.fg, sp = c.error, underline = true },
	StatusLine = { fg = c.fg, bg = c.bg },
	StatusLineNC = { fg = c.none, bg = c.none },
	TabLine = { fg = c.fg, bg = c.bg },
	TabLineFill = { fg = c.fg, bg = c.bg },
	TabLineSel = { fg = c.fg, bg = c.bg },
	Title = { fg = c.fg, bg = c.bg },
	Visual = { fg = c.selection, reverse = true },
	VisualNOS = { fg = c.selection, reverse = true },
	WarningMsg = { fg = c.accent, reverse = true },
	Whitespace = { fg = c.fg_idle },
	Winseparator = { bg = c.bg, fg = c.fg_idle },
	WildMenu = { bg = c.selection, fg = c.fg },

	Comment = { fg = c.comment, italic = true },

	Constant = { fg = c.constant },
	String = { fg = c.string },
	Character = { fg = c.string },
	Number = { fg = c.constant },
	Boolean = { fg = c.constant },
	Float = { fg = c.constant },

	Identifier = { fg = c.fg },
	Function = { fg = c.func },

	Statement = { fg = c.special },
	Conditional = { fg = c.special },
	Repeat = { fg = c.special },
	Label = { fg = c.special },
	Operator = { fg = c.operator },
	Keyword = { fg = c.keyword },
	Exception = { fg = c.special },

	PreProc = { fg = c.keyword },
	Include = { fg = c.keyword },
	Define = { fg = c.keyword },
	Macro = { fg = c.keyword },
	PreCondit = { fg = c.keyword },

	Type = { fg = c.keyword },
	StorageClass = { fg = c.keyword },
	Structure = { fg = c.keyword },
	Typedef = { fg = c.keyword },

	Special = { fg = c.fg_idle },
	SpecialChar = { fg = c.constant },
	Tag = { fg = c.tag },
	Delimiter = { fg = c.markup },
	SpecialComment = { fg = c.comment, italic = true },
	Debug = { fg = c.func },

	Underlined = { underline = true },
	Ignore = { fg = c.fg },
	Error = { fg = c.error },
	Todo = { fg = c.fg, reverse = true, bold = true },
}

return theme
